# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-25 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0002_auto_20170825_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eqlayout',
            name='eq_name',
        ),
        migrations.AddField(
            model_name='eqlayout',
            name='cn_name',
            field=models.CharField(default='', max_length=50, verbose_name='机台中文名称'),
        ),
        migrations.AddField(
            model_name='eqlayout',
            name='en_name',
            field=models.CharField(default='', max_length=50, verbose_name='机台英文名称'),
        ),
    ]
