# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-25 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0003_auto_20170825_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='end_point',
            field=models.CharField(default='', max_length=15, verbose_name='终点坐标'),
        ),
        migrations.AddField(
            model_name='path',
            name='start_point',
            field=models.CharField(default='', max_length=15, verbose_name='起点坐标'),
        ),
    ]
