# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-28 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0004_auto_20170825_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='path',
            name='floor',
        ),
        migrations.AddField(
            model_name='path',
            name='end_floor',
            field=models.CharField(choices=[('L10', 'L10'), ('L20', 'L20'), ('L30', 'L30'), ('L40', 'L40')], default='楼层未选', max_length=10, verbose_name='终点楼层'),
        ),
        migrations.AddField(
            model_name='path',
            name='start_floor',
            field=models.CharField(choices=[('L10', 'L10'), ('L20', 'L20'), ('L30', 'L30'), ('L40', 'L40')], default='楼层未选', max_length=10, verbose_name='起点楼层'),
        ),
        migrations.AlterField(
            model_name='eqlayout',
            name='cn_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='机台中文名称'),
        ),
        migrations.AlterField(
            model_name='path',
            name='path_node',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='路径节点坐标'),
        ),
    ]
