# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-29 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0005_auto_20170828_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eqlayout',
            name='vertex',
            field=models.CharField(max_length=500, verbose_name='顶点坐标'),
        ),
        migrations.AlterField(
            model_name='path',
            name='path_node',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='路径节点坐标'),
        ),
    ]
